### ISSUE TITLE
Design Docs

### ISSUE THREAD

**Issue by ronilbhatia** [jameshawkinsjr/hype#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
- [x] Contains a link/placeholder for a link to the live page
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

## Comments
* Great job! Your home page is formatted a little bit different than how we suggest but I think it's organized and makes sense!
---

# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] Includes the following list for the 4 app specific MVPs:
  - [x] Adequate styling
  - [x] Smooth, bug-free navigation
  - [x] Adequate and appropriate seeds to demonstrate the feature
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

## Comments
* Missing User Auth, Heroku, and Production README
* Missing bullets for each core MVP stating what each MVP will include -> you can use the ones suggested above (adequate styling, smooth bug-free navigation, adequate and appropriate seeds)
* Explicitly state which MVPs are will have the full CRUD cycle.
* Add time estimates for how long each MVP will take to complete and on what day you expect to be done with it by
---

# Database Schema

- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
    - [x] indexed
    - [x] foreign key
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
    - [x] the table header column names are bolded
    - [x] columns names are lowercased and snaked_cased and `back_ticked`

## Comments
* Backtick column names in tables.
* You won't need a `profile_photo` column -> you will be utilizing an ActiveStorage association in Rails that will allow you to host your images on AWS. We can discuss this more when we meet next Tuesday, but you will not need this column.
* A bit confused about the indexing in your messages table. None of your foreign keys are indexed, but `body` is? I would think that this would be entirely flipped. All your foreign keys should be indexed as a general rule of thumb unless you have an extremely compelling reason not to.
* Everything from `stars` down should be a bonus feature and you should not work on those until you have completed your MVPs.
* Not too many comments apart from that, looks like you've put thought into this and covered most of the bases. You will need to utilize something called ActionCable in order to implement live chat in your app -> I've personally never used it before but again this is something we can discuss when we meet next Tuesday.
---

# Sample State

- [x] State shape is flat!
- [x] State's keys are camelCased
- [x] All keys within the values in the state are accessible in the schema
- [x] Correctly formatted
    - [x] Sample state is rendered with triple backticks, and the language ` ```javascript...``` `). This will display the state as a code block instead of a giant line of text 
    - [x] Top level slices
        - [x] `entities`
        - [x] `session`
        - [x] `errors` (here or in `ui`)
        - [x] `ui` (if needed)
    - [x] Should NOT have nested slices, aka  `comments` inside of `posts`
      + Some info from other tables is ok, for instance:
        + the author username and imageurl for a post. basically any info that the user can't change
        + like count and a boolean on whether the user likes the post instead of a likes slice

## Comments
* Really good job. I have pretty much nothing to say here. If I were to be really nitpicky some of your foreign keys have 'ID' with both letters capitalized and it should probably just be 'Id' instead to follow camelCase conventions. But that's me looking really hard to find something to improve. The content itself is looking like exactly what you'll need.
---

# Backend Routes

- [x] Contains the following sections: HTML, API Endpoints(Backend)
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Routes does not contain [superfluous routes](https://github.com/appacademy/curriculum/blob/master/rails/readings/routing-part-ii.md)
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint because that info comes through the post show

## Comments
* Will your `GET /api/users` route be used for your search functionality?
* It might be worth it to have a `GET /api/chatrooms/:chatroom_id/messages` route that would return all of the messages for a given chatroom. You would trigger this API call once the user entered the chatroom. If you had another idea about this, we can talk about it though.
* Back-end routes should use snake_case rather than camelCase :)
* Good job not having superfluous routes!
---

# Frontend Routes

- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

## Comments
* At first I was a little confused about the nesting of your routes, but after looking at the Slack Web App I think I understand and am in line with what you are doing. The only thing I noticed is that it looks like Slack has it set up so that the `EditUserForm` is actually a modal (you'll notice when you go to edit your profile the URL doesn't change no matter where you are). I won't force you to do this, if you prefer just having a separate route => though I would say if you do this I don't see a reason for having this route be nested. If you're interested in making it a Modal like Slack does you can check out the ModalBnB resource in the full-stacks section of the curriculum. Ultimately though, this isn't a big deal as this route should probably be a bonus.

**Comment by jameshawkinsjr** [comment]
>  Backtick column names in tables.

Good to go

> You won't need a `profile_photo` column -> you will be utilizing an ActiveStorage association in Rails that will allow you to host your images on AWS. We can discuss this more when we meet next Tuesday, but you will not need this column.

Good to go

> A bit confused about the indexing in your messages table. None of your foreign keys are indexed, but `body` is? I would think that this would be entirely flipped. All your foreign keys should be indexed as a general rule of thumb unless you have an extremely compelling reason not to.

My thought process was that the search functionality would search the contents of messages, but you wouldn't be searching for them by chatroom, author, or parent -- but now that you've mentioned it, I'm realizing that the loading of messages in each chatroom is why you need to index them.

> Everything from `stars` down should be a bonus feature and you should not work on those until you have completed your MVPs.

Sounds good

>  Not too many comments apart from that, looks like you've put thought into this and covered most of the bases. You will need to utilize something called ActionCable in order to implement live chat in your app -> I've personally never used it before but again this is something we can discuss when we meet next Tuesday.

Sounds good - I'll start looking into it.

**Comment by jameshawkinsjr** [comment]
> MVP List

I think you reviewed before I made my final edits -- I finalized & updated according to your notes

>Sample State
> some of your foreign keys have 'ID' 

Fixed

> Backend Routes
> * Will your `GET /api/users` route be used for your search functionality?

Yes - just included that as well

> * It might be worth it to have a `GET /api/chatrooms/:chatroom_id/messages` route that would return all of the messages for a given chatroom. You would trigger this API call once the user entered the chatroom. If you had another idea about this, we can talk about it though.

I hadn't added it to avoid nesting API routes & was curious if I could achieve the same thing by hitting my `GET /api/messages` endpoint and providing the `chatroom_id`, or if that's unnecessary.

> * Back-end routes should use snake_case rather than camelCase :)

Fixed

> * `EditUserForm` is actually a modal

I noticed that too and was thinking that I wanted to make it a modal, but put it down as a frontend route for simplicity and thought I could revisit if I make it that far.

**Comment by ronilbhatia** [comment]
Closing this issue!
