### ISSUE TITLE
User Auth Requirements

### ISSUE THREAD

**Issue by jameshawkinsjr** [jameshawkinsjr/hype#2]
# User Auth

## Functionality

- [x] The main button with logo should link to `/`
- [x] Has working demo login

### Before Login

- [x] The `/login` page should not display a link to `Log In`. Same for `/signup`
- [x] Going to a random route `/#/oweiniouewbrviuwebv` should redirect or display a 404 page
- [x] Errors should display for both `/signup` and `/login`.
- [x] Errors should clear when moving between `/signup` and `/login`.
- [x] Can sign up a user
- [x] Can sign in as a user
- [x] Can log out a user
- [x] Can't sign up with the same username/email
- [x] Pressing enter after filling out the session form should use the form data, not the demo user

### After Login

- [x] Should not be able to visit `/login` or `/signup`
- [x] Should be able to refresh the page and still be logged in

## Style

- [x] The site should look exactly like the actual site
- [x] All relevant elements should have `cursor: pointer` on hover
- [x] When errors are displayed, most elements should not move around the page (particularly input boxes)
- [x] Remove Redux logger and all console.log()'s from production

---
## Comments
* A lot of text on your site says 'Slack' instead of 'Hype'. In the nav bar, main portion of your page, and the footer.
* Right now, if I try to visit signup or login after being logged in, it takes me back to your Splash page, which isn't ideal, since it just gives me links to signup and login. Should probably redirect back to the user's chatroom dashboard instead.
* Your error rendering is different than Slack's. I don't mind it because it looks nice and doesn't move elements around the page, but Slack seems to display a box up top with the errors, whereas yours are just adding them to the bottom of the form. I know the bullet says rendering errors shouldn't move elements around the page, but it's preferred if the design matches the website your cloning. I won't force you to change this, though.
![screen shot 2019-02-28 at 10 09 49 am](https://user-images.githubusercontent.com/32026924/53588271-62528900-3b41-11e9-92b9-d0ee6f693f96.png)
![screen shot 2019-02-28 at 10 10 04 am](https://user-images.githubusercontent.com/32026924/53588272-62528900-3b41-11e9-84dc-ba09853faed3.png)
* I get this blue outline when I click on the input box which is different than Slack's. You can change this by using the `:focus` pseudo-selector, and changing the `outline` property.
![screen shot 2019-02-28 at 9 58 33 am](https://user-images.githubusercontent.com/32026924/53587634-bd837c00-3b3f-11e9-83e4-9301926889f0.png)
![screen shot 2019-02-28 at 9 58 41 am](https://user-images.githubusercontent.com/32026924/53587635-bd837c00-3b3f-11e9-8fc1-1c7e9d4e5418.png)
* Text is a little scrunched up for these demo users
![screen shot 2019-02-28 at 10 03 49 am](https://user-images.githubusercontent.com/32026924/53587809-2e2a9880-3b40-11e9-9032-411cd23d9b9a.png)

**Comment by ronilbhatia** [comment]
Hey James,

Overall really great job so far! The splash page looks awesome, and the styling is super on point. Also it's awesome that you got your own domain for it, especially this early on. Pretty much all the functionality is there, but I have some suggestions above ranked in order of importance. The issue can be closed out after you address the first two bullets, and the last 3 would just be suggestions.

**Comment by jameshawkinsjr** [comment]
> A lot of text on your site says 'Slack' instead of 'Hype'. In the nav bar, main portion of your page, and the footer.

**Fixed**

> Right now, if I try to visit signup or login after being logged in, it takes me back to your Splash page, which isn't ideal, since it just gives me links to signup and login. Should probably redirect back to the user's chatroom dashboard instead.

**Just updated my ProtectedRoute to redirect to /chatrooms -- the original way was more inline w/ Slack's routing, but I do prefer it this way.**

> Your error rendering is different than Slack's. I don't mind it because it looks nice and doesn't move elements around the page, but Slack seems to display a box up top with the errors, whereas yours are just adding them to the bottom of the form. I know the bullet says rendering errors shouldn't move elements around the page, but it's preferred if the design matches the website your cloning. I won't force you to change this, though.

_**Fixed**_

>  I get this blue outline when I click on the input box which is different than Slack's. You can change this by using the `:focus` pseudo-selector, and changing the `outline` property.

_**Fixed**_

>  Text is a little scrunched up for these demo users

_**Fixed**_

**Comment by ronilbhatia** [comment]
Sweet, good job man! Closing this issue. Only other thing I'd suggest is a link on the 'login' page to take you to 'signup' and vice versa.
