### ISSUE TITLE
Direct Message Requirements

### ISSUE THREAD

**Issue by jameshawkinsjr** [jameshawkinsjr/hype#5]
# Messages

### Create

- [x] Users can direct message other members
- [x] Direct messages persist to the server upon creation
- [x] Once a direct message has been created, other users can't be added

### Read

- [x] A user can see the other person they are direct messaging
- [x] A marker indicates if there are unread messages for a direct message thread
- [x] Direct message threads are unique (You can't have multiple direct messages with the same 2 users)

### Update

- [ ] A user can edit the topic of a direct message

### Delete

- [x] User can leave a direct message thread

## Style

- [x] The direct message should look exactly like the actual site
- [x] When errors are displayed, most elements should not move around the page
- [x] Remove Redux logger and all console.log()'s from production

**Comment by ronilbhatia** [comment]
I don't think you need the 'editing topic' for a direct message? This looks awesome man, fantastic job.
