### ISSUE TITLE
User & Chatroom Search Requirements

### ISSUE THREAD

**Issue by jameshawkinsjr** [jameshawkinsjr/hype#6]
# Messages

### Jump to button

- [x] Clicking on the "Jump To" button opens a modal that allows you to search through available channels

### User search

- [x] A user can search through a list of users to add to direct message threads
- [x] When clicking on a user, that user gets added to the input box
- [x] When clicking on a selected user, that user is removed from the input box

### Channel Search

- [x] A user can search through a list of channels to join

## Style

- [x] The search tools should look exactly like the real site

**Comment by ronilbhatia** [comment]
You killed it.
